// Shared demo seed data — used by seed-demo.ts
// All fictional people and companies

export const HERO_PARTICIPANTS = [
  { name: 'Sarah Chen', email: 'sarah.chen@acmecorp.com', isHost: true },
  { name: 'Ahmed Khan', email: 'ahmed.khan@acmecorp.com' },
  { name: 'Marcus Webb', email: 'marcus.webb@northstar.io' },
  { name: 'Priya Patel', email: 'priya.patel@northstar.io' },
  { name: 'Jordan Lee', email: 'jordan.lee@acmecorp.com' },
  { name: 'David Kim', email: 'david.kim@northstar.io' },
  { name: 'Rachel Torres', email: 'rachel.torres@acmecorp.com' },
  { name: 'Sam Nguyen', email: 'sam.nguyen@northstar.io' },
]

export const HERO_TRANSCRIPT: Array<{ speaker: string; startMs: number; endMs: number; text: string }> = [
  // ─── INTRO & AGENDA (0:00–5:00) ───────────────────────────────────────────
  { speaker: 'Sarah Chen', startMs: 0, endMs: 12000, text: "Good morning everyone, thanks for joining. Let's get started on the Northstar implementation planning. We have a lot to cover today." },
  { speaker: 'Marcus Webb', startMs: 13000, endMs: 24000, text: "Thanks Sarah. From our side at Northstar, we're feeling good about the overall timeline but we have some concerns about the Okta SSO integration that I want to make sure we address today." },
  { speaker: 'Ahmed Khan', startMs: 25000, endMs: 38000, text: "Agreed. The SSO piece is really the critical path here. Everything else can proceed in parallel, but until SSO is validated, we can't do the pilot launch." },
  { speaker: 'Sarah Chen', startMs: 39000, endMs: 54000, text: "Right, so let me walk through today's agenda quickly. We have SSO, data migration status, security review, training plan, pricing, contract, and a few open issues to close. I'd like to end with a confirmed critical path. Does everyone have a copy of the project tracker?" },
  { speaker: 'David Kim', startMs: 55000, endMs: 65000, text: "Yes, I pulled it up. I want to flag upfront that I have a hard stop at noon Eastern, so if we need to push anything to a follow-up, let's plan for that." },
  { speaker: 'Priya Patel', startMs: 66000, endMs: 78000, text: "Same here, noon is my limit today. Sarah, maybe we can timebox each section? I'm worried we'll spend too much time on SSO and not get to the contract amendment questions." },
  { speaker: 'Sarah Chen', startMs: 79000, endMs: 92000, text: "Good call. Let's try to keep each topic to about ten minutes. I'll be the timekeeper. Ahmed, can you take notes on the action items?" },
  { speaker: 'Ahmed Khan', startMs: 93000, endMs: 101000, text: "Absolutely, I've got a running document open. Ready to go." },
  { speaker: 'Rachel Torres', startMs: 102000, endMs: 113000, text: "Quick note from me — the training content team sent over the final module recordings yesterday, so we now have everything ready on our side. I'll give a full update during the training section." },
  { speaker: 'Sam Nguyen', startMs: 114000, endMs: 124000, text: "And I have a pricing update that will only take two minutes, but it's blocking the billing integration testing, so I'd like to get that decision today if possible." },
  { speaker: 'Sarah Chen', startMs: 125000, endMs: 137000, text: "Perfect. We'll definitely get to that. Okay, let's start with Okta SSO since it's the critical path. Jordan, you've been in the technical weeds on this — want to give us the current status?" },

  // ─── SSO DEEP DIVE (5:00–18:00) ───────────────────────────────────────────
  { speaker: 'Jordan Lee', startMs: 138000, endMs: 154000, text: "Sure. So our SSO implementation is based on the Auth0 multi-tenant SAML bridge we've built for other enterprise customers. The core code is solid. The complication here is that Northstar has three separate Okta tenants across business units, and we need to route based on email domain." },
  { speaker: 'Priya Patel', startMs: 155000, endMs: 167000, text: "I want to understand the scope better. Are we talking about full Okta integration with SCIM provisioning, or just SAML SSO? Because those have very different timelines." },
  { speaker: 'Jordan Lee', startMs: 168000, endMs: 182000, text: "We scoped for SAML SSO in phase one. SCIM provisioning is in the roadmap for Q2 next year. But the SAML implementation itself has some complexity because Northstar has a multi-tenant Okta org." },
  { speaker: 'Marcus Webb', startMs: 183000, endMs: 199000, text: "That's correct. We have three business units each with their own Okta tenant. We need the platform to support routing based on email domain to the correct tenant. Has your team handled that before?" },
  { speaker: 'Ahmed Khan', startMs: 200000, endMs: 217000, text: "Yes, we have a multi-tenant SSO architecture. It's not trivial but it's solved. The question is whether we can get the Okta configuration from each business unit in time. We need the metadata XML from each tenant at least two weeks before the go-live." },
  { speaker: 'David Kim', startMs: 218000, endMs: 235000, text: "Our IT security team typically takes one to two weeks for any changes to Okta config because it has to go through a change management process. So if we submit the request this week, we should be okay for October 1st, but there's no buffer." },
  { speaker: 'Jordan Lee', startMs: 236000, endMs: 253000, text: "Can I ask — is the change management process the same for all three business units? Because if each unit has its own IT team and their own review cycle, we're looking at potentially three separate change requests on three different timelines." },
  { speaker: 'David Kim', startMs: 254000, endMs: 270000, text: "That's a great point. The Midwest unit uses our central IT process. East and West have their own IT organizations that are partially autonomous. East unit is generally faster, West unit has historically been slower." },
  { speaker: 'Marcus Webb', startMs: 271000, endMs: 288000, text: "West is slow because they had a security incident two years ago and they significantly tightened their change management process. It's actually something I'm proud of, but it does create delays for projects like this." },
  { speaker: 'Priya Patel', startMs: 289000, endMs: 305000, text: "This is a concern. If West unit's IT can't deliver by October 1st, can we launch without West unit initially and add them in a second phase?" },
  { speaker: 'Ahmed Khan', startMs: 306000, endMs: 323000, text: "Technically yes. We can configure the system to only accept logins from Midwest and East initially. West users would see an access denied page with an explanation. But that's a business decision, not a technical one." },
  { speaker: 'Marcus Webb', startMs: 324000, endMs: 341000, text: "I think a two-phase SSO launch is acceptable. We actually considered that from the start. Midwest first, East and West to follow. Sarah, are you okay with phasing the SSO configuration?" },
  { speaker: 'Sarah Chen', startMs: 342000, endMs: 356000, text: "I'm okay with it if it's clearly documented and there's a firm commitment on when West comes online. We don't want a situation where phase two keeps getting pushed. What's a realistic date for West?" },
  { speaker: 'David Kim', startMs: 357000, endMs: 374000, text: "If West submits this week, I'd estimate their change management cycle at three to four weeks. So November 1st is realistic for West unit SSO. Which actually aligns with the November 1st fallback date we've been discussing." },
  { speaker: 'Ahmed Khan', startMs: 375000, endMs: 391000, text: "Let's lock that in. October 15th: Midwest and East SSO live. November 1st: West unit SSO completes. I'll add this to the project plan and make sure it's reflected in the implementation timeline." },
  { speaker: 'Jordan Lee', startMs: 392000, endMs: 409000, text: "One more thing on SSO — we need to confirm the just-in-time provisioning behavior. When a new user logs in via SSO for the first time, should we auto-create their account with a default role, or should they go through an approval workflow?" },
  { speaker: 'Priya Patel', startMs: 410000, endMs: 426000, text: "Northstar's governance requires an approval workflow for system access. But I recognize that creates friction. Could we do auto-provisioning with a viewer-only role and require approval to upgrade to editor?" },
  { speaker: 'Jordan Lee', startMs: 427000, endMs: 443000, text: "That works perfectly. Auto-provision as viewer, admin approves role elevation. We already support that pattern. Priya, I'll need the admin approver list — probably a small group of super admins per business unit?" },
  { speaker: 'Priya Patel', startMs: 444000, endMs: 458000, text: "Yes. I'll send you the list by end of this week. We have two to three admins per unit. I'll cc David since he's coordinating the Midwest rollout." },
  { speaker: 'Sarah Chen', startMs: 459000, endMs: 471000, text: "Marcus, can you commit to getting us the Okta metadata from Midwest and East tenants by October 1st?" },
  { speaker: 'Marcus Webb', startMs: 472000, endMs: 487000, text: "Yes. I'll personally chase the IT leads in both units this afternoon. Midwest should be no problem. For East, I may need to escalate to their IT director but I have a good relationship there." },
  { speaker: 'David Kim', startMs: 488000, endMs: 502000, text: "I'll submit the formal change management requests for all three units today. That starts the clock. I'll copy the project distribution list on all submissions so everyone can track." },
  { speaker: 'Sarah Chen', startMs: 503000, endMs: 515000, text: "Great. SSO looks like we have a path. Ahmed, note that. Next topic — data migration. Rachel, want to hand this one to David since he's leading it now?" },

  // ─── DATA MIGRATION (18:00–30:00) ────────────────────────────────────────
  { speaker: 'Rachel Torres', startMs: 516000, endMs: 531000, text: "I want to flag the data migration piece upfront. We're migrating about 18 months of historical data from the legacy system. We haven't finalized the field mapping yet and that's a blocker for the migration team." },
  { speaker: 'Priya Patel', startMs: 532000, endMs: 547000, text: "The field mapping was supposed to be complete by last Friday. What happened? We've been waiting on the data specification from Northstar for three weeks now." },
  { speaker: 'Marcus Webb', startMs: 548000, endMs: 563000, text: "I apologize for that delay. We had a resource issue — the person who was leading the data mapping exercise took a leave of absence. David has been ramping up on it this week." },
  { speaker: 'David Kim', startMs: 564000, endMs: 580000, text: "Yes, I've taken over the data mapping work. I can commit to having the draft field mapping document to your team by end of this week, Wednesday at the latest. There are some edge cases around the legacy system's custom fields that I want to discuss separately." },
  { speaker: 'Ahmed Khan', startMs: 581000, endMs: 596000, text: "Wednesday works. Let's schedule a technical call Thursday morning to go through the edge cases. I'll need our data engineering lead on that call — is that okay with your team?" },
  { speaker: 'David Kim', startMs: 597000, endMs: 611000, text: "Thursday morning works. What time? We're Eastern, your team is Pacific?" },
  { speaker: 'Ahmed Khan', startMs: 612000, endMs: 624000, text: "We can do ten am Eastern, seven am Pacific. I'll block time for Julia from our data engineering team. She knows the migration codebase inside and out." },
  { speaker: 'Rachel Torres', startMs: 625000, endMs: 641000, text: "Can you give us a preview of what the edge cases are, David? I want to make sure our migration scripts can handle them. We have a few custom field types that don't map cleanly to our schema." },
  { speaker: 'David Kim', startMs: 642000, endMs: 659000, text: "Sure. The main ones are: the legacy system has a custom field called AccountStatus with about forty enumerated values that don't map one-to-one to your status taxonomy. And we have some records with compound customer IDs — like a prefix-dash-number format — that may collide with your auto-generated UUID system." },
  { speaker: 'Rachel Torres', startMs: 660000, endMs: 676000, text: "The compound ID issue is potentially a problem. We use UUIDs for all primary keys. If the legacy IDs need to be preserved as external references, we'd need to add a legacy ID column to several tables. Ahmed, is that feasible?" },
  { speaker: 'Ahmed Khan', startMs: 677000, endMs: 694000, text: "Yes. We should add a legacy_external_id nullable text column to the relevant tables. It's a small schema change but it needs to be done before we run migrations. I can have that in a migration script by Friday." },
  { speaker: 'Jordan Lee', startMs: 695000, endMs: 712000, text: "What's the volume of records we're talking about? 18 months of data from a company Northstar's size could be hundreds of thousands of records. We need to make sure the migration runs within a reasonable time window." },
  { speaker: 'David Kim', startMs: 713000, endMs: 730000, text: "We estimated approximately 280,000 customer records, about 1.2 million transaction records, and 400,000 interaction records. The bulk of the data is in the transaction table." },
  { speaker: 'Rachel Torres', startMs: 731000, endMs: 748000, text: "1.2 million transactions is manageable but we'll want to run it in batches. Have you done a dry run export from the legacy system yet? We need a sample data set to test the migration scripts against." },
  { speaker: 'David Kim', startMs: 749000, endMs: 765000, text: "Not yet. I can get IT to export a 10% sample — about 120,000 transaction records — by Monday. Would that be enough to validate the migration approach before we run the full extract?" },
  { speaker: 'Ahmed Khan', startMs: 766000, endMs: 782000, text: "A 10% sample is great for validation. Please make sure it includes edge cases — records with null fields, records at the maximum length for text columns, and a few of those compound IDs we discussed. That's usually where migration scripts break." },
  { speaker: 'David Kim', startMs: 783000, endMs: 799000, text: "I'll specifically request edge case records in the sample export. I know the data team can filter for those." },
  { speaker: 'Sam Nguyen', startMs: 800000, endMs: 815000, text: "What's the blackout window for the actual migration? Are we doing a cutover migration where the old system goes read-only while we migrate, or are we doing a parallel run?" },
  { speaker: 'Rachel Torres', startMs: 816000, endMs: 832000, text: "We were planning a cutover migration during a maintenance window. The legacy system would go read-only, we'd run the migration, run validation checks, and then flip the switch. Total window would be about six to eight hours." },
  { speaker: 'Marcus Webb', startMs: 833000, endMs: 849000, text: "A six to eight hour maintenance window on a weekend is acceptable. We'd need at least two weeks advance notice to communicate to our users. So if we're planning October 15th go-live, we need to lock the migration weekend by October 1st." },
  { speaker: 'Sarah Chen', startMs: 850000, endMs: 866000, text: "Let's tentatively plan the migration for the weekend of October 12th — Saturday night. That gives two days of buffer before Monday October 15th go-live. If anything goes wrong in migration, we have Sunday to fix it." },
  { speaker: 'Ahmed Khan', startMs: 867000, endMs: 882000, text: "Saturday October 12th migration, Monday October 15th go-live. That works. We'll need the sample data by Monday October 7th to have time to validate the scripts. So David's Thursday data delivery is essential." },
  { speaker: 'David Kim', startMs: 883000, endMs: 897000, text: "Understood. Let me also flag that our IT team needs a formal change request to export production data, even a sample. I'll initiate that today. Could take a day or two to approve." },
  { speaker: 'Sarah Chen', startMs: 898000, endMs: 911000, text: "Good to have that visibility. Let's move to security review. This one I know has some time pressure too." },

  // ─── SECURITY REVIEW (30:00–40:00) ───────────────────────────────────────
  { speaker: 'Priya Patel', startMs: 912000, endMs: 929000, text: "Our security team does a vendor assessment for any system that handles customer financial data. You're going to be processing payment information as part of the billing integration, so this is required by our security policy. We use a third-party pen testing firm." },
  { speaker: 'Jordan Lee', startMs: 930000, endMs: 947000, text: "We've been through several of these. Can your security team share the testing methodology and scope in advance? We typically need at least two weeks notice before a pen test so we can coordinate with our infrastructure team and make sure we're testing in a staging environment." },
  { speaker: 'Priya Patel', startMs: 948000, endMs: 964000, text: "Yes, I can get you the scope document next week. But I want to flag that if any critical vulnerabilities are found, we won't be able to proceed with go-live until they're remediated. That could affect the October timeline." },
  { speaker: 'Ahmed Khan', startMs: 965000, endMs: 983000, text: "Understood. We take security seriously and we've had clean pen test results in the past. But we should build remediation time into the schedule. If we assume testing happens in the last week of September, we should have findings by early October, with a week or two for any remediations." },
  { speaker: 'Jordan Lee', startMs: 984000, endMs: 1001000, text: "Our last third-party pen test was six months ago. The testing firm found three low-severity findings and zero high or critical. We remediated all three within a week. I can share the report if that helps your team's confidence level." },
  { speaker: 'Priya Patel', startMs: 1002000, endMs: 1019000, text: "I'd actually love to have that report. Our security team will want to review it as part of their due diligence. Can you send it to me and our CISO directly? His email is ciso at northstar dot io." },
  { speaker: 'Jordan Lee', startMs: 1020000, endMs: 1033000, text: "I'll send it today. I'll cc Sarah and Ahmed as well." },
  { speaker: 'Marcus Webb', startMs: 1034000, endMs: 1051000, text: "I want to make sure the scope of the pen test is reasonable. What systems will be in scope? We don't want the testing firm to have broad access to our Northstar internal systems — just the Acme platform that will hold our data." },
  { speaker: 'Priya Patel', startMs: 1052000, endMs: 1068000, text: "The scope will be limited to the Acme platform production-equivalent staging environment. Northstar's own infrastructure is not in scope. The testing firm will work from the same access perspective as one of our end users." },
  { speaker: 'Ahmed Khan', startMs: 1069000, endMs: 1086000, text: "That's a black-box test then. We can also provide a white-box option where we give the testing firm access to our deployment configuration, which typically leads to more thorough results. Would Northstar's security team prefer that?" },
  { speaker: 'Priya Patel', startMs: 1087000, endMs: 1103000, text: "White-box would actually be preferred by our CISO. He believes it gives a more accurate assessment. But it requires your team to provide credentials and documentation, which is a bigger ask." },
  { speaker: 'Ahmed Khan', startMs: 1104000, endMs: 1119000, text: "White-box is fine. We'll prepare a documentation package including our AWS architecture diagram, IAM policies, network topology, and application security controls. It will take a day to compile. When do you need it by?" },
  { speaker: 'Priya Patel', startMs: 1120000, endMs: 1135000, text: "If testing is the last week of September, we'd need documentation to the firm at least a week before — so September 22nd. Can you commit to that?" },
  { speaker: 'Ahmed Khan', startMs: 1136000, endMs: 1149000, text: "September 22nd is tight but doable. I'll assign Jordan and our DevSecOps lead to put that together." },
  { speaker: 'Sarah Chen', startMs: 1150000, endMs: 1163000, text: "That puts us at risk for October 15th if there are any significant findings. Let's discuss the contingency plan. What are our options if we need to slip the launch date?" },
  { speaker: 'Marcus Webb', startMs: 1164000, endMs: 1181000, text: "Pushing to November 1st would work from our side. We have a board presentation in mid-November that we'd like to be able to show live data in the new system. So November 1st is our hard deadline — if we miss that, we're looking at Q1 of next year." },
  { speaker: 'Rachel Torres', startMs: 1182000, endMs: 1198000, text: "November 1st as a fallback gives us two additional weeks. I think that's manageable as long as the SSO and data migration pieces resolve on schedule. The training program is actually ready — we built out the training materials and recorded the video walkthroughs last week." },
  { speaker: 'Priya Patel', startMs: 1199000, endMs: 1215000, text: "I should also mention — our security team has a review cycle of its own. Even after pen test results come in, our CISO needs to sign off. That review typically takes three to five business days. So findings on October 7th means CISO sign-off around October 12th at the earliest." },
  { speaker: 'Sarah Chen', startMs: 1216000, endMs: 1231000, text: "So if findings come in October 7th and CISO reviews by October 12th, and any high findings need to be remediated, we're right at the edge of October 15th. The schedule is tight but not impossible." },
  { speaker: 'Ahmed Khan', startMs: 1232000, endMs: 1248000, text: "Here's what I'd propose: we run the pen test September 24th through 26th. We request a preliminary findings report by September 28th for any critical or high issues. If critical findings exist, we escalate immediately and start remediation while we wait for the full report." },
  { speaker: 'Priya Patel', startMs: 1249000, endMs: 1264000, text: "I can ask the testing firm if they can do a preliminary readout. Most firms accommodate that for enterprise clients. I'll make it part of the scope requirements." },
  { speaker: 'Jordan Lee', startMs: 1265000, endMs: 1280000, text: "I want to add one thing — can we agree that medium and low findings do not block go-live, only high and critical? Having a clear severity threshold in writing will make the go/no-go decision much cleaner." },
  { speaker: 'Priya Patel', startMs: 1281000, endMs: 1297000, text: "That's a reasonable proposal. I'll need to confirm with our CISO, but typically we apply the same threshold. Medium findings go on a remediation roadmap with a 90-day SLA. I'll get confirmation and add it to the project agreement." },
  { speaker: 'Sarah Chen', startMs: 1298000, endMs: 1310000, text: "Okay, security looks like we have a plan. Let's move to training." },

  // ─── TRAINING & ROLLOUT (40:00–47:00) ───────────────────────────────────
  { speaker: 'Rachel Torres', startMs: 1311000, endMs: 1328000, text: "Training is actually in great shape. We completed all five training modules and the video walkthroughs are recorded. The live training sessions are designed to be two hours each, covering the platform from an admin perspective and then from an end-user perspective." },
  { speaker: 'Jordan Lee', startMs: 1329000, endMs: 1345000, text: "On the training side, I want to make sure we think about the rollout sequence. We're recommending a phased rollout — start with one business unit, run for two weeks, then expand to the other two. Does that work with your expectations?" },
  { speaker: 'David Kim', startMs: 1346000, endMs: 1362000, text: "A phased rollout makes sense. Our Midwest business unit is the smallest and most straightforward, so we suggest starting there. They have about 150 users versus 400 and 600 in the East and West units respectively." },
  { speaker: 'Priya Patel', startMs: 1363000, endMs: 1379000, text: "I support the phased approach but I want to make sure the rollout plan is captured in the contract amendment. We have contractual commitments around uptime and data availability that need to apply from day one, even for the pilot unit." },
  { speaker: 'Rachel Torres', startMs: 1380000, endMs: 1396000, text: "For the Midwest training sessions, we're planning three sessions of two hours each — Monday and Wednesday over three weeks starting October 21st. That gives users a few days to use the system before the next session where we can address questions." },
  { speaker: 'David Kim', startMs: 1397000, endMs: 1413000, text: "That schedule works for Midwest. But I want to make sure we have training materials available in self-serve format as well. Not everyone can attend live sessions, and our remote workers in the Midwest unit are spread across four time zones." },
  { speaker: 'Rachel Torres', startMs: 1414000, endMs: 1430000, text: "We have a full self-serve package: the video walkthroughs, a written quick-start guide, and a comprehensive help center article set. All of it will be accessible from within the platform under a Help section. I can also give David a pre-launch preview to share with his admins." },
  { speaker: 'Marcus Webb', startMs: 1431000, endMs: 1447000, text: "The self-serve materials are important. Our Midwest users are used to learning software on their own — they're a tech-savvy group. Live sessions are helpful for admins but the general user population will mostly use the self-serve resources." },
  { speaker: 'Sarah Chen', startMs: 1448000, endMs: 1463000, text: "We'll make sure the help center is indexed and searchable from day one. Rachel, can you do an internal walkthrough of the training content with David's team before go-live — like an admin pre-training?" },
  { speaker: 'Rachel Torres', startMs: 1464000, endMs: 1478000, text: "Absolutely. I'd suggest scheduling that for the week of October 7th, after the migration sample data is validated but before the migration weekend. That way the admins are trained on real data workflows." },
  { speaker: 'David Kim', startMs: 1479000, endMs: 1493000, text: "October 7th week works. Tuesday or Wednesday would be ideal — I'll confirm by tomorrow." },
  { speaker: 'Jordan Lee', startMs: 1494000, endMs: 1509000, text: "Do we have translation requirements? Northstar's West unit has a significant Spanish-speaking user base, and some of the content may need to be available in Spanish." },
  { speaker: 'Marcus Webb', startMs: 1510000, endMs: 1527000, text: "Yes, Spanish localization for the West unit. But that's a phase two requirement for us — we don't need it for the initial Midwest launch. It should be on the product roadmap though." },
  { speaker: 'Ahmed Khan', startMs: 1528000, endMs: 1543000, text: "Noted. We'll add Spanish localization to the Q1 roadmap for West unit launch. I'll make sure it's referenced in the product agreement so it doesn't get lost." },

  // ─── PRICING (47:00–53:00) ────────────────────────────────────────────────
  { speaker: 'Sam Nguyen', startMs: 1544000, endMs: 1560000, text: "I can share an update on the pricing configuration. We've completed the base pricing tier setup and the discount rules are in the system. The one outstanding item is the enterprise volume discount table that Marcus's team needs to review and approve." },
  { speaker: 'Marcus Webb', startMs: 1561000, endMs: 1577000, text: "Sorry Sam, I know we've been slow on that. I'll personally review the discount table this week and send you our approval or any changes by Friday. That's been sitting too long." },
  { speaker: 'Sam Nguyen', startMs: 1578000, endMs: 1593000, text: "Thank you Marcus. Once we have the pricing approval, we can finalize the billing integration testing. We're blocked on that right now, but the code is ready to go." },
  { speaker: 'Priya Patel', startMs: 1594000, endMs: 1611000, text: "I'd like to understand the pricing structure a bit better for my own knowledge. Is it seat-based, usage-based, or some combination?" },
  { speaker: 'Sam Nguyen', startMs: 1612000, endMs: 1629000, text: "The Northstar contract is seat-based with a minimum seat commitment. The volume discount table provides tiered discounts at 500, 1000, and 2000 seats. Since Northstar has about 1,150 total users across all business units, you'd be in the 1000-seat tier." },
  { speaker: 'Marcus Webb', startMs: 1630000, endMs: 1646000, text: "That matches my understanding from the sales process. The 1000-seat tier discount was a key part of the commercial negotiation. I just want to verify that the discount is applied correctly in the system before we finalize the contract." },
  { speaker: 'Sam Nguyen', startMs: 1647000, endMs: 1662000, text: "Correct. The pricing table in the approval document maps to the exact rates in the contract. It's a sanity check — just needs your eyes on it to confirm nothing got lost in translation from the negotiation." },
  { speaker: 'David Kim', startMs: 1663000, endMs: 1679000, text: "Marcus, should I be involved in reviewing the discount table? I'm doing the broader finance coordination for this project, and I want to make sure the numbers match what's in our procurement system." },
  { speaker: 'Marcus Webb', startMs: 1680000, endMs: 1694000, text: "Yes, include David on that review loop. Sam, can you send the pricing table to both of us today?" },
  { speaker: 'Sam Nguyen', startMs: 1695000, endMs: 1707000, text: "I'll send it this afternoon. It's a simple spreadsheet — two columns, seat ranges and monthly rate per seat. Five minutes to review." },
  { speaker: 'Sarah Chen', startMs: 1708000, endMs: 1722000, text: "Great. Marcus, can you commit to Friday for the pricing approval?" },
  { speaker: 'Marcus Webb', startMs: 1723000, endMs: 1734000, text: "Yes, Friday is committed. If there are any discrepancies I'll flag them Thursday so we have time to resolve." },
  { speaker: 'Sam Nguyen', startMs: 1735000, endMs: 1750000, text: "Thank you. One more thing on billing — the invoicing integration will generate monthly invoices automatically based on seat count. The first invoice will go out on November 1st for the October usage. Is billing handled centrally at Northstar or per business unit?" },
  { speaker: 'David Kim', startMs: 1751000, endMs: 1766000, text: "Centrally. All invoices should go to our AP department with a copy to me. I'll send you the AP contact and PO number when we finalize." },
  { speaker: 'Sam Nguyen', startMs: 1767000, endMs: 1779000, text: "Perfect. I'll configure the billing contact before go-live." },

  // ─── CONTRACT (53:00–57:00) ────────────────────────────────────────────────
  { speaker: 'Sarah Chen', startMs: 1780000, endMs: 1797000, text: "Legal is reviewing the contract amendment now. We expect to have the updated language to you by end of this week. Priya, can your legal team prioritize a quick review? We need it signed before we can proceed with the go-live." },
  { speaker: 'Priya Patel', startMs: 1798000, endMs: 1815000, text: "I'll flag it as urgent with our general counsel. In my experience, if we get them a clean draft by Thursday, they can turnaround in 48 hours. So that should be aligned with the October timeline." },
  { speaker: 'Marcus Webb', startMs: 1816000, endMs: 1833000, text: "The two main changes in the contract amendment, as I recall, are: the phased rollout schedule we've now confirmed, and the SLA for the Midwest pilot unit specifically. Are there other open items?" },
  { speaker: 'Sarah Chen', startMs: 1834000, endMs: 1851000, text: "There's also language around the data migration warranty — we're committing to data integrity validation post-migration and a defined reconciliation period. And the security pen test completion as a go-live condition." },
  { speaker: 'Priya Patel', startMs: 1852000, endMs: 1869000, text: "On the security pen test language — we need to be specific about what constitutes a blocker. Can we say 'no high or critical severity findings unresolved at time of go-live'? That's the threshold we agreed on earlier." },
  { speaker: 'Sarah Chen', startMs: 1870000, endMs: 1884000, text: "Yes, I'll make sure that specific language is in the amendment. High and critical findings as go-live blockers, medium and low on a 90-day remediation SLA." },
  { speaker: 'Jordan Lee', startMs: 1885000, endMs: 1901000, text: "Can we also add a clause about the West unit SSO delivery date? November 1st for West unit as a committed milestone, not just a target. If we don't hit it, there should be a defined cure period." },
  { speaker: 'Priya Patel', startMs: 1902000, endMs: 1918000, text: "That's fair. A 30-day cure period for missed milestones is standard in our contracts. But I want to make sure the milestone only applies to what's in Acme's control — if the West unit IT delay is on our side, we don't want Acme to be penalized for it." },
  { speaker: 'Sarah Chen', startMs: 1919000, endMs: 1935000, text: "Agreed. We'll draft the milestone language to distinguish between Acme's obligations and Northstar's dependencies. If Northstar IT doesn't deliver the Okta metadata, the November 1st milestone clock pauses." },
  { speaker: 'Marcus Webb', startMs: 1936000, endMs: 1950000, text: "That's a reasonable approach. Legal review should catch any ambiguity. Let's move on — I want to make sure we get to the critical path summary." },

  // ─── OPEN ISSUES (57:00–61:00) ────────────────────────────────────────────
  { speaker: 'Ahmed Khan', startMs: 1951000, endMs: 1969000, text: "Let me summarize the critical path as I understand it: SSO metadata by October 1st, security pen test in the last week of September with findings by October 7th, data migration field mapping by Wednesday, pricing approval by Friday, contract amendment signed by end of next week. Does that capture the key dependencies?" },
  { speaker: 'Marcus Webb', startMs: 1970000, endMs: 1988000, text: "That's accurate from my perspective. I'd add that we need the training schedule finalized this week as well, so our business unit admins can start blocking time on their calendars for the Midwest rollout." },
  { speaker: 'Rachel Torres', startMs: 1989000, endMs: 2005000, text: "I can have the training schedule to David by tomorrow EOD. We're planning three sessions of two hours each — Monday and Wednesday over three weeks. So starting October 21st for the Midwest group." },
  { speaker: 'Sam Nguyen', startMs: 2006000, endMs: 2022000, text: "One thing I want to raise before we close — the staging environment performance. We've been seeing some slowness in the staging environment during the load testing we did last week. Nothing that affects the go-live, but it's something we should track." },
  { speaker: 'Ahmed Khan', startMs: 2023000, endMs: 2040000, text: "Yes, I saw the performance report. We have some N+1 query issues in the reporting module that are causing the slowness under load. We expect to have that resolved in the release next Tuesday. It won't affect the go-live timeline." },
  { speaker: 'Jordan Lee', startMs: 2041000, endMs: 2057000, text: "Do we have performance benchmarks that Northstar's team expects us to meet? We should validate that the production environment meets those benchmarks before go-live." },
  { speaker: 'Priya Patel', startMs: 2058000, endMs: 2075000, text: "Our SLA is in the contract: 99.9% uptime, page load times under 2 seconds for standard operations, report generation under 5 seconds for reports with up to 10,000 rows. We'll want to see those benchmarks verified in the staging environment with production-equivalent data volumes." },
  { speaker: 'Ahmed Khan', startMs: 2076000, endMs: 2093000, text: "We can schedule a load test the week of October 7th with production data volumes — after the migration sample arrives. I'll have the benchmark results in a report format that Priya's team can review for the SLA validation." },
  { speaker: 'Sam Nguyen', startMs: 2094000, endMs: 2109000, text: "Good. Also, one small thing — we need Northstar to whitelist our IP ranges for the data migration. We sent those over two weeks ago but haven't gotten confirmation." },
  { speaker: 'David Kim', startMs: 2110000, endMs: 2126000, text: "I apologize, that fell through the cracks. I'll escalate to our IT team immediately after this call. We should have confirmation by end of day today." },
  { speaker: 'Jordan Lee', startMs: 2127000, endMs: 2143000, text: "There's also the question of the API credentials for our integration. We need production API keys for the Northstar data sources that we'll be polling. Those were requested three weeks ago as well." },
  { speaker: 'David Kim', startMs: 2144000, endMs: 2160000, text: "Same situation — I inherited these open items from my predecessor. I'm going to do a full audit of everything that's pending on Northstar's side today and send an action item list by end of day. I want to close all of these outstanding items this week." },
  { speaker: 'Marcus Webb', startMs: 2161000, endMs: 2178000, text: "David, I appreciate that. Please loop in our IT director directly — his name is Frank Chen. He can expedite anything that needs escalation. I'll send you an intro today." },
  { speaker: 'David Kim', startMs: 2179000, endMs: 2192000, text: "Thank you Marcus. Having that direct line will make a big difference." },
  { speaker: 'Sarah Chen', startMs: 2193000, endMs: 2209000, text: "Let's make sure that release note gets shared with Northstar's team so they're aware of the performance fix. Any other blockers or concerns before we close?" },

  // ─── UAT PLANNING (37:00–44:00) ──────────────────────────────────────────
  { speaker: 'Sarah Chen', startMs: 2210000, endMs: 2226000, text: "Before we move to final commitments, I want to make sure we have a clear user acceptance testing plan. Who owns UAT on the Northstar side?" },
  { speaker: 'David Kim', startMs: 2227000, endMs: 2735000, text: "I'm the UAT coordinator for the Midwest pilot. I've put together a test script covering the key user workflows — account lookup, transaction history, report generation, and SSO login. I can share that with your team today." },
  { speaker: 'Rachel Torres', startMs: 2736000, endMs: 2752000, text: "That's great. On our side, we'll assign a QA lead to work alongside David's team during UAT. We typically run a structured UAT for five business days before go-live sign-off." },
  { speaker: 'Marcus Webb', startMs: 2753000, endMs: 2769000, text: "How many test users will we have in the UAT environment? I want to make sure the Midwest team has enough seats provisioned so all the testers can log in simultaneously." },
  { speaker: 'Ahmed Khan', startMs: 2770000, endMs: 2786000, text: "We'll provision 20 test accounts in the UAT environment for Midwest. That should cover your pilot testing group. The UAT environment will be isolated from production with a copy of the migration sample data." },
  { speaker: 'David Kim', startMs: 2787000, endMs: 2803000, text: "20 seats is more than enough for our UAT group. We were planning for about 12 testers — a mix of power users and occasional users. The key test scenarios we want to validate are the SSO login flow, the reporting module, and the billing reconciliation view." },
  { speaker: 'Jordan Lee', startMs: 2804000, endMs: 2820000, text: "I'll set up the UAT environment by October 7th — same day as the admin pre-training. That way David's team can do a walkthrough during the training and then go into structured UAT the following week." },
  { speaker: 'Priya Patel', startMs: 2821000, endMs: 2838000, text: "UAT sign-off is a contractual requirement for go-live, correct? I want to make sure that's in the project plan as a gate." },
  { speaker: 'Sarah Chen', startMs: 2839000, endMs: 2855000, text: "Yes, it's in the project plan and will be in the contract amendment. UAT sign-off is required from David as the named Northstar representative before we flip the go-live switch." },
  { speaker: 'David Kim', startMs: 2856000, endMs: 2872000, text: "Understood. I'll have the sign-off authority. If UAT reveals issues, I'll escalate to Marcus rather than hold up the process while we debug. We want to be a constructive partner here, not a bottleneck." },
  { speaker: 'Ahmed Khan', startMs: 2873000, endMs: 2889000, text: "Thank you David, that's exactly the right attitude. We'll have a bug triage process where anything found in UAT gets triaged within 4 hours. Critical issues get same-day fixes where possible." },
  { speaker: 'Rachel Torres', startMs: 2890000, endMs: 2906000, text: "One thing I'd add to UAT — let's make sure the training content is available in the UAT environment as well. We've found that testers do better when they have the quick-start guide open alongside the application." },
  { speaker: 'David Kim', startMs: 2907000, endMs: 2921000, text: "Agreed. We'll make the help documentation available in a shared folder for the UAT team before the sessions start." },

  // ─── RISK REGISTER (44:00–50:00) ─────────────────────────────────────────
  { speaker: 'Sarah Chen', startMs: 2922000, endMs: 2938000, text: "Good. Let's do a quick risk register pass before we close. I want to make sure we've captured the top risks and who owns mitigation. Ahmed, can you walk us through the current risk list?" },
  { speaker: 'Ahmed Khan', startMs: 2939000, endMs: 2956000, text: "Sure. Top risks as I see them: one, Okta metadata delay for West unit — impact is West unit can't go live October 15th, mitigation is the two-phase SSO plan we agreed. Owner: David Kim and Marcus Webb." },
  { speaker: 'Ahmed Khan', startMs: 2957000, endMs: 2973000, text: "Two, critical pen test finding — impact is go-live blocked, mitigation is early results September 28th and pre-emptive remediation planning. Owner: Jordan Lee for technical remediation, Priya Patel for Northstar acceptance." },
  { speaker: 'Ahmed Khan', startMs: 2974000, endMs: 2990000, text: "Three, data migration field mapping errors — impact is corrupt or missing data post-migration, mitigation is sample data validation October 7th through 11th before we run production migration. Owner: Rachel Torres for migration scripts, David Kim for data validation." },
  { speaker: 'Marcus Webb', startMs: 2991000, endMs: 3007000, text: "I want to add a fourth risk that hasn't come up today — we have a parallel ERP upgrade happening in our East business unit in mid-October. There's a small chance the ERP project creates IT bandwidth constraints that slow down the Northstar platform rollout to East." },
  { speaker: 'Ahmed Khan', startMs: 3008000, endMs: 3024000, text: "That's a real risk. What's the probability and timing?" },
  { speaker: 'Marcus Webb', startMs: 3025000, endMs: 3041000, text: "I'd call it 20% probability. The ERP cutover is planned for October 18th — three days after our go-live. If East IT gets overwhelmed, they might defer our rollout by a week. I'd rate it medium risk." },
  { speaker: 'Sarah Chen', startMs: 3042000, endMs: 3058000, text: "Let's note that as a watch item. If it materializes, we adjust the East rollout to November 1st alongside West. The Midwest go-live is still October 15th in all scenarios." },
  { speaker: 'Priya Patel', startMs: 3059000, endMs: 3075000, text: "There's one more risk from our side — our general counsel is on vacation the week of September 22nd. Contract review and sign-off may be delayed if there are material issues with the amendment language." },
  { speaker: 'Sarah Chen', startMs: 3076000, endMs: 3092000, text: "Is there a backup approver? We need someone who can sign the amendment." },
  { speaker: 'Priya Patel', startMs: 3093000, endMs: 3109000, text: "Yes, our associate general counsel has authority for vendor contracts under five million dollars. This falls within that threshold. I'll make sure she's briefed and available." },
  { speaker: 'Jordan Lee', startMs: 3110000, endMs: 3126000, text: "One technical risk to note — our staging and production environments share a network segment for the SSO callback endpoint. If the pen testing firm's scans are aggressive, they could accidentally disrupt the SSO configuration in production. We should put a testing window in place." },
  { speaker: 'Ahmed Khan', startMs: 3127000, endMs: 3143000, text: "Good catch Jordan. I'll create a testing subnet specifically for the pen test scope and make sure the testing firm's IPs are blocked from the production SSO endpoints during their testing window." },
  { speaker: 'David Kim', startMs: 3144000, endMs: 2668000, text: "That's reassuring. Our IT security team will also be monitoring during the pen test window. They'll want the testing firm's IP ranges in advance so they can distinguish authorized testing traffic from genuine attack attempts." },
  { speaker: 'Priya Patel', startMs: 2669000, endMs: 2685000, text: "I'll get the testing firm's IP ranges from them when we confirm the scope next week and share them with your team and David's IT security contacts." },
  { speaker: 'Sarah Chen', startMs: 2686000, endMs: 2700000, text: "Perfect. Risk register looks comprehensive. Ahmed, add these to the tracker. Let's move to final commitments and close out." },

  // ─── FINAL CHECK-IN & COMMITMENTS (50:00–54:14) ──────────────────────────
  { speaker: 'Priya Patel', startMs: 2701000, endMs: 2718000, text: "I want to flag one more risk. We have a Northstar all-hands meeting on October 3rd where our CEO will announce the new platform rollout to the entire company. That's an external commitment now. Missing October 15th would create significant internal friction for our leadership." },
  { speaker: 'Sarah Chen', startMs: 2719000, endMs: 2735000, text: "We understand the weight of that. We're committed to the October 15th date. The plan we've laid out today is aggressive but executable if everyone delivers on their commitments." },
  { speaker: 'Marcus Webb', startMs: 2736000, endMs: 2753000, text: "I want to formally record that Northstar is committed to delivering our side of the dependencies: Okta metadata for Midwest and East by October 1st, data migration field mapping by Wednesday, pricing approval by Friday, and IP whitelist confirmation today." },
  { speaker: 'Ahmed Khan', startMs: 2754000, endMs: 2771000, text: "And from Acme Corp: security documentation by September 22nd, legacy ID schema changes by Friday, migration scripts ready for sample data validation, benchmark report by October 10th, and the contract amendment draft by Thursday." },
  { speaker: 'Rachel Torres', startMs: 2772000, endMs: 2787000, text: "And training: admin pre-training week of October 7th, training schedule to David tomorrow, user training sessions October 21st through November 1st." },
  { speaker: 'Jordan Lee', startMs: 2788000, endMs: 2804000, text: "I'll add one technical commitment from our side: SSO configuration complete in staging by September 30th, ready for Northstar testing before go-live. We'll need someone from Northstar's IT to validate the SSO flow end-to-end in staging." },
  { speaker: 'David Kim', startMs: 2805000, endMs: 2820000, text: "I'll be that person for SSO validation. I have enough technical background to run through the login flow and confirm it works. When can we expect staging to be ready?" },
  { speaker: 'Jordan Lee', startMs: 2821000, endMs: 2834000, text: "Staging will be configured as soon as we receive the Okta metadata. Assuming October 1st delivery, I can have staging SSO ready by October 3rd for your testing." },
  { speaker: 'Priya Patel', startMs: 2835000, endMs: 2851000, text: "October 3rd is the all-hands day. Could we do October 4th for SSO validation in staging? I'd like David focused on the all-hands communications on October 3rd." },
  { speaker: 'David Kim', startMs: 2852000, endMs: 2864000, text: "October 4th works perfectly for me." },
  { speaker: 'Marcus Webb', startMs: 2865000, endMs: 2882000, text: "I want to also request a project status dashboard or shared tracker that everyone can see. Right now the status lives in different documents and emails. Can we have a single source of truth?" },
  { speaker: 'Sarah Chen', startMs: 2883000, endMs: 2899000, text: "We'll set up a shared project tracker in our project management tool and give Northstar read access. Ahmed, can you take care of that today?" },
  { speaker: 'Ahmed Khan', startMs: 2900000, endMs: 2915000, text: "Yes, I'll set it up in our Notion workspace and share it by end of day. It will have all the milestones, owners, due dates, and status — green, yellow, red." },
  { speaker: 'Sarah Chen', startMs: 2916000, endMs: 2932000, text: "Perfect. I'll send a meeting invite for Monday at 10am Eastern for our weekly check-in. These will be 30-minute standing calls until go-live. Let's keep them tight — 15 minutes of status update, 15 minutes of issue resolution." },
  { speaker: 'Marcus Webb', startMs: 2933000, endMs: 2949000, text: "Monday check-ins work for our side. I'd also like to have a dedicated Slack channel for urgent items. Not for status updates but for blockers that can't wait until Monday." },
  { speaker: 'Ahmed Khan', startMs: 2950000, endMs: 2965000, text: "We already have that channel set up — it's the Northstar-Acme-Project channel. I'll add Marcus, Priya, and David if they're not already in there." },
  { speaker: 'David Kim', startMs: 2966000, endMs: 2980000, text: "I'm in there already. Marcus and Priya, I'll send you the invite link." },
  { speaker: 'Sarah Chen', startMs: 2981000, endMs: 2997000, text: "We will make it happen. Thank you all for a productive call. This was exactly the kind of alignment session we needed. Ahmed, can you take the notes and action items? I'll add any follow-ups from my end." },
  { speaker: 'Ahmed Khan', startMs: 2998000, endMs: 3015000, text: "On it. I'll have the full action item list out within an hour of the call, with owners and due dates. I'll also update the Notion tracker at the same time." },
  { speaker: 'Marcus Webb', startMs: 3016000, endMs: 3032000, text: "I want to formally record that we're committed to the October 15th launch date with November 1st as the hard fallback. Northstar has allocated significant internal resources to this project and we're counting on Acme Corp to deliver. Thank you everyone." },
  { speaker: 'Priya Patel', startMs: 3033000, endMs: 3049000, text: "Agreed. One final note from our side — if anything comes up between now and Monday that could affect the critical path, please don't wait. Use the Slack channel or call me directly." },
  { speaker: 'Jordan Lee', startMs: 3050000, endMs: 3063000, text: "Understood. Same from our side." },
  { speaker: 'Rachel Torres', startMs: 3064000, endMs: 3076000, text: "Looking forward to a great launch. Thanks everyone." },
  { speaker: 'Sam Nguyen', startMs: 3077000, endMs: 3088000, text: "Thanks all, talk Monday." },
  { speaker: 'David Kim', startMs: 3089000, endMs: 3100000, text: "Thanks everyone. I'll be busy today!" },
  { speaker: 'Ahmed Khan', startMs: 3101000, endMs: 3113000, text: "Talk to everyone next Monday. Thank you." },
  { speaker: 'Sarah Chen', startMs: 3114000, endMs: 3125000, text: "Have a great rest of the week, everyone. Bye." },
  { speaker: 'Marcus Webb', startMs: 3126000, endMs: 3136000, text: "Thank you everyone. Looking forward to a successful launch." },
  { speaker: 'Priya Patel', startMs: 3137000, endMs: 3145000, text: "Thanks, have a great day." },
]

export const HERO_SUMMARY = {
  overview: "Acme Corp and Northstar held an enterprise implementation planning call covering the critical path to the October 15th go-live date. Key topics included Okta SSO integration complexity with Northstar's multi-tenant environment, data migration field mapping delays, security penetration testing requirements, pricing configuration approval, training schedule, and contract amendment status. A November 1st hard fallback date was established, with the October 3rd all-hands announcement creating additional urgency for the primary date.",
  keyPoints: [
    "Okta SSO integration is the critical path — requires metadata from all 3 business unit tenants by October 1st; West unit may slip to November 1st due to slower change management",
    "Two-phase SSO launch agreed: Midwest and East go live October 15th, West unit follows November 1st",
    "Security pen test planned for September 24–26; white-box assessment with documentation package required by September 22nd",
    "High and critical pen test findings block go-live; medium and low go on 90-day remediation SLA",
    "Data migration field mapping delayed due to resource issue; David Kim committed to Wednesday delivery",
    "Sample data export (10% of records) needed by Monday October 7th for migration script validation",
    "Pricing enterprise discount table approval needed from Marcus Webb by Friday",
    "Phased rollout starting with Midwest business unit (150 users) recommended; East and West to follow",
    "Contract amendment under legal review; expected to Northstar by Thursday; CISO sign-off by end of next week",
    "Performance issues in staging environment (N+1 queries in reporting) to be fixed in Tuesday release",
    "IP whitelist and API credentials pending from Northstar IT; David Kim escalating today",
    "Northstar CEO announcing platform rollout at October 3rd all-hands, creating external deadline",
  ],
  decisions: [
    { text: "October 15th primary go-live date with November 1st as hard fallback deadline", status: 'confirmed' as const },
    { text: "Two-phase SSO launch: Midwest and East on October 15th, West unit on November 1st", status: 'confirmed' as const },
    { text: "Phased rollout: start with Midwest business unit (150 users), then expand to East and West", status: 'confirmed' as const },
    { text: "White-box security pen test to occur September 24–26 using Northstar's third-party firm", status: 'confirmed' as const },
    { text: "High and critical severity pen test findings block go-live; medium and low go on 90-day SLA", status: 'confirmed' as const },
    { text: "SAML SSO only in phase 1; SCIM provisioning deferred to Q2 next year", status: 'confirmed' as const },
    { text: "Spanish localization for West unit added to Q1 product roadmap", status: 'tentative' as const },
    { text: "Training sessions: three 2-hour sessions, Monday/Wednesday, starting October 21st for Midwest", status: 'confirmed' as const },
    { text: "Auto-provision new SSO users as viewer role; require admin approval to upgrade to editor", status: 'confirmed' as const },
  ],
  actionItems: [
    { text: "Submit Okta SSO change management requests for all three business units", owner: 'David Kim', dueDate: '2025-09-15' },
    { text: "Chase IT leads in Midwest and East for Okta metadata delivery by October 1st", owner: 'Marcus Webb', dueDate: '2025-09-15' },
    { text: "Send previous pen test report to Priya Patel and Northstar CISO", owner: 'Jordan Lee', dueDate: '2025-09-15' },
    { text: "Deliver draft data migration field mapping document", owner: 'David Kim', dueDate: '2025-09-17' },
    { text: "Schedule and run technical data migration call to review edge cases", owner: 'Ahmed Khan', dueDate: '2025-09-18' },
    { text: "Review and approve enterprise volume discount table", owner: 'Marcus Webb', dueDate: '2025-09-19' },
    { text: "Prepare white-box security documentation package (AWS architecture, IAM, network topology)", owner: 'Ahmed Khan', dueDate: '2025-09-22' },
    { text: "Send Northstar the security pen test scope document", owner: 'Priya Patel', dueDate: '2025-09-22' },
    { text: "Deliver updated contract amendment to Northstar's legal team", owner: 'Sarah Chen', dueDate: '2025-09-18' },
    { text: "Confirm CISO sign-off threshold (high/critical block go-live) in project agreement", owner: 'Priya Patel', dueDate: '2025-09-19' },
    { text: "Finalize and send training schedule to David Kim", owner: 'Rachel Torres', dueDate: '2025-09-16' },
    { text: "Add legacy_external_id column migration script to schema", owner: 'Ahmed Khan', dueDate: '2025-09-19' },
    { text: "Escalate IP whitelist and API credentials requests to IT director", owner: 'David Kim', dueDate: '2025-09-15' },
    { text: "Send Northstar intro to IT director Frank Chen", owner: 'Marcus Webb', dueDate: '2025-09-15' },
    { text: "Set up shared Notion project tracker with milestone status and share with Northstar", owner: 'Ahmed Khan', dueDate: '2025-09-15' },
    { text: "Send meeting invite for Monday 10am Eastern weekly check-ins", owner: 'Sarah Chen', dueDate: '2025-09-15' },
    { text: "Resolve N+1 query issues in reporting module for Tuesday release", owner: 'Ahmed Khan', dueDate: '2025-09-23' },
    { text: "Configure SSO in staging environment once Okta metadata received", owner: 'Jordan Lee', dueDate: '2025-10-03' },
    { text: "Validate SSO flow end-to-end in staging environment", owner: 'David Kim', dueDate: '2025-10-04' },
    { text: "Request 10% sample data export from legacy system including edge cases", owner: 'David Kim', dueDate: '2025-09-17' },
  ],
  topics: [
    { title: 'Agenda & Meeting Setup', summary: 'Sarah set the agenda covering SSO, data migration, security review, training, pricing, and contract. Priya and David flagged noon hard stops. Rachel announced training materials are complete.', startMs: 0, endMs: 137000 },
    { title: 'Okta SSO Integration', summary: 'Multi-tenant Okta setup with three separate tenant orgs. Two-phase SSO agreed: Midwest and East by October 1st metadata delivery, West unit follows November 1st due to slower change management. Auto-provision as viewer with admin role elevation. Admin approver list needed from Priya.', startMs: 138000, endMs: 515000 },
    { title: 'Data Migration', summary: 'Field mapping delayed due to resource issue; David Kim taking over, commits to Wednesday delivery. Technical call Thursday to address edge cases including compound IDs and AccountStatus enum mapping. Legacy external ID column needed in schema. 10% sample data export requested. Cutover migration planned for Saturday October 12th.', startMs: 516000, endMs: 911000 },
    { title: 'Security Review', summary: 'White-box pen test September 24–26 using Northstar's third-party firm. Security documentation package required by September 22nd. High and critical findings block go-live; medium and low on 90-day SLA. CISO review takes 3–5 business days after findings. Previous clean pen test report to be shared proactively.', startMs: 912000, endMs: 1310000 },
    { title: 'Training & Rollout', summary: 'Training materials complete: 5 modules plus video walkthroughs and help center articles. Three 2-hour live sessions Monday/Wednesday starting October 21st for Midwest. Admin pre-training week of October 7th. Self-serve materials for remote workers. Spanish localization added to Q1 roadmap for West unit.', startMs: 1311000, endMs: 1543000 },
    { title: 'Pricing & Billing', summary: 'Base pricing and discount rules complete. Enterprise volume discount table at 1000-seat tier pending Marcus approval by Friday. Billing integration testing blocked pending pricing approval. Central invoicing to AP department, first invoice November 1st.', startMs: 1544000, endMs: 1779000 },
    { title: 'Contract Amendment', summary: 'Amendment covers phased rollout schedule, Midwest pilot SLA, data migration warranty, and pen test completion language. High/critical findings language to be explicitly included. West unit SSO November 1st milestone with 30-day cure period but pauses if Northstar IT delays. Expected signature by end of next week.', startMs: 1780000, endMs: 1950000 },
    { title: 'Open Issues & Infrastructure', summary: 'IP whitelist for data migration overdue from Northstar IT. API credentials still pending. Performance N+1 query fix in Tuesday release. Load test planned week of October 7th against SLA benchmarks (99.9% uptime, <2s pages, <5s reports). Shared Notion tracker to be set up today.', startMs: 1951000, endMs: 2209000 },
    { title: 'Final Commitments & Close', summary: 'All parties formally committed to critical path items. Monday 10am Eastern weekly check-ins scheduled. Shared Slack channel confirmed for urgent blockers. Ahmed to send full action item list within one hour. October 3rd all-hands announcement confirmed as external pressure point.', startMs: 2701000, endMs: 3145000 },
  ],
  highlights: [
    { title: 'SSO Is The Critical Path', startMs: 200000, endMs: 217000 },
    { title: 'Two-Phase SSO Agreed', startMs: 324000, endMs: 391000 },
    { title: 'Pen Test Could Delay Launch', startMs: 948000, endMs: 1019000 },
    { title: 'High/Critical Findings Block Go-Live', startMs: 1265000, endMs: 1297000 },
    { title: 'November 1st Hard Fallback', startMs: 1164000, endMs: 1198000 },
    { title: 'CEO All-Hands Announcement Context', startMs: 2210000, endMs: 2753000 },
    { title: 'Marcus Formal Commitment', startMs: 2736000, endMs: 2753000 },
  ],
}

export const SEED_MEETINGS = [
  {
    title: 'Weekly Product Sync',
    durationMs: 38 * 60 * 1000,
    participants: [
      { name: 'Elena Rodriguez', email: 'elena@techflow.io', isHost: true },
      { name: 'Ben Carter', email: 'ben@techflow.io' },
      { name: 'Lena Park', email: 'lena@techflow.io' },
      { name: 'Alex Morrison', email: 'alex@techflow.io' },
      { name: 'Jamie Walsh', email: 'jamie@techflow.io' },
      { name: 'Chris Okafor', email: 'chris@techflow.io' },
    ],
    summary: "Weekly sync covering sprint velocity, three new feature flags shipped to production, and discussion of the upcoming API versioning strategy. Team agreed to deprecate v1 endpoints by March next year.",
    actionItems: [
      { text: 'Update API deprecation timeline in documentation', owner: 'Chris Okafor' },
      { text: 'Schedule architecture review for v2 API design', owner: 'Alex Morrison' },
      { text: 'Share sprint metrics with leadership by Friday', owner: 'Elena Rodriguez' },
    ],
  },
  {
    title: 'Customer Discovery — Redwood Financial',
    durationMs: 47 * 60 * 1000,
    participants: [
      { name: 'Maya Singh', email: 'maya@acmecorp.com', isHost: true },
      { name: 'Tom Bradley', email: 'tom@redwoodfinancial.com' },
      { name: 'Lisa Chen', email: 'lisa@redwoodfinancial.com' },
      { name: 'Kevin Park', email: 'kevin@acmecorp.com' },
      { name: 'Nadia Osei', email: 'nadia@redwoodfinancial.com' },
    ],
    summary: "Discovery call with Redwood Financial exploring their compliance reporting challenges. Key pain points: manual report generation taking 3-4 days per quarter, data spread across 6 different systems, audit trail gaps. Strong fit for automated reporting and data consolidation capabilities.",
    actionItems: [
      { text: 'Send product demo recording and pricing proposal', owner: 'Maya Singh' },
      { text: 'Prepare compliance automation case studies', owner: 'Kevin Park' },
      { text: 'Schedule technical deep dive with Redwood IT team', owner: 'Maya Singh' },
    ],
  },
  {
    title: 'Candidate Interview — Backend Engineer',
    durationMs: 52 * 60 * 1000,
    participants: [
      { name: 'Diana Chen', email: 'diana@techflow.io', isHost: true },
      { name: 'Arjun Sharma', email: 'arjun.sharma@candidate.com' },
      { name: 'Robert Kim', email: 'robert@techflow.io' },
    ],
    summary: "Technical interview with Arjun Sharma for the Senior Backend Engineer role. Strong performance on distributed systems design question. Concerns about depth of experience with PostgreSQL query optimization. Demonstrated excellent problem-solving approach and communication skills. Recommend advancing to final round with engineering leadership.",
    actionItems: [
      { text: 'Submit candidate evaluation form to recruiting', owner: 'Diana Chen' },
      { text: 'Schedule final round panel interview', owner: 'Diana Chen' },
      { text: 'Send take-home assessment in parallel', owner: 'Robert Kim' },
    ],
  },
  {
    title: 'Design Review — Dashboard Redesign',
    durationMs: 34 * 60 * 1000,
    participants: [
      { name: 'Sofia Martinez', email: 'sofia@techflow.io', isHost: true },
      { name: 'Jake Thompson', email: 'jake@techflow.io' },
      { name: 'Yuki Tanaka', email: 'yuki@techflow.io' },
      { name: 'Mia Johnson', email: 'mia@techflow.io' },
      { name: 'Caleb Foster', email: 'caleb@techflow.io' },
    ],
    summary: "Design review of the new analytics dashboard. Approved the data visualization approach and chart library selection. Feedback to increase information density in the summary cards and reconsider the color system for accessibility compliance. Next step: update Figma prototypes and schedule engineering handoff.",
    actionItems: [
      { text: 'Update dashboard Figma with higher density layout', owner: 'Sofia Martinez' },
      { text: 'Run color contrast accessibility audit', owner: 'Yuki Tanaka' },
      { text: 'Create engineering specification document', owner: 'Jake Thompson' },
    ],
  },
  {
    title: 'Founder 1:1 — Q4 Planning',
    durationMs: 41 * 60 * 1000,
    participants: [
      { name: 'Nathan Brooks', email: 'nathan@techflow.io', isHost: true },
      { name: 'Olivia Zhang', email: 'olivia@techflow.io' },
    ],
    summary: "Quarterly planning session covering revenue targets, hiring priorities, and strategic focus areas. Agreed to prioritize enterprise segment in Q4, pause mid-market expansion until Q1. Three VP-level hires to close before December: VP Sales, VP Customer Success, and Head of Engineering.",
    actionItems: [
      { text: 'Begin VP Sales search, open JD by Monday', owner: 'Nathan Brooks' },
      { text: 'Update board deck with Q4 targets and hiring plan', owner: 'Olivia Zhang' },
      { text: 'Schedule board call for October 20th', owner: 'Olivia Zhang' },
    ],
  },
  {
    title: 'Sprint Planning — Sprint 43',
    durationMs: 56 * 60 * 1000,
    participants: [
      { name: 'Marcus Lee', email: 'marcus@techflow.io', isHost: true },
      { name: 'Sarah Kim', email: 'sarah.k@techflow.io' },
      { name: 'Dylan Russo', email: 'dylan@techflow.io' },
      { name: 'Aisha Patel', email: 'aisha@techflow.io' },
      { name: 'Erik Svensson', email: 'erik@techflow.io' },
      { name: 'Priya Rajan', email: 'priya.r@techflow.io' },
      { name: 'Leo Nakamura', email: 'leo@techflow.io' },
    ],
    summary: "Sprint 43 planning with 52 story points committed. Key deliverables: complete notification system refactor, ship audit logging MVP, and begin work on the export functionality. Carried over 8 points from sprint 42 related to auth service edge cases. Team velocity stable at 48-55 points.",
    actionItems: [
      { text: 'Finalize notification service API contract before Monday standup', owner: 'Dylan Russo' },
      { text: 'Set up export module scaffold and share PR', owner: 'Sarah Kim' },
      { text: 'Document auth service edge cases for knowledge base', owner: 'Erik Svensson' },
    ],
  },
  {
    title: 'Customer Success Check-in — Vertex Analytics',
    durationMs: 29 * 60 * 1000,
    participants: [
      { name: 'Hannah Moore', email: 'hannah@acmecorp.com', isHost: true },
      { name: 'Tyler Grant', email: 'tyler@vertexanalytics.com' },
      { name: 'Chloe Bennett', email: 'chloe@vertexanalytics.com' },
      { name: 'James Liu', email: 'james@acmecorp.com' },
    ],
    summary: "Quarterly business review with Vertex Analytics. NPS score improved from 6 to 8 since last quarter. Two open support tickets resolved. Discussion of expanding usage to the European team. Renewal in 3 months — customer expressed satisfaction and intent to renew with potential seat expansion.",
    actionItems: [
      { text: 'Prepare European expansion pricing proposal', owner: 'James Liu' },
      { text: 'Share updated roadmap highlighting European data residency', owner: 'Hannah Moore' },
      { text: 'Schedule renewal discussion for next month', owner: 'Hannah Moore' },
    ],
  },
  {
    title: 'Pricing Review — Enterprise Tier Restructure',
    durationMs: 45 * 60 * 1000,
    participants: [
      { name: 'Rebecca Stone', email: 'rebecca@techflow.io', isHost: true },
      { name: 'Daniel Park', email: 'daniel@techflow.io' },
      { name: 'Amy Chen', email: 'amy@techflow.io' },
      { name: 'Victor Okafor', email: 'victor@techflow.io' },
      { name: 'Simone Laurent', email: 'simone@techflow.io' },
      { name: 'Chris Tanaka', email: 'chris.t@techflow.io' },
    ],
    summary: "Pricing committee review of proposed enterprise tier restructure. Decision to move from seat-based to usage-based pricing for enterprise customers with 500+ seats. New model includes a base platform fee plus consumption tiers. Expected to improve gross margin by 8-12 points. Rollout to existing customers with 6-month grandfathering period.",
    actionItems: [
      { text: 'Model financial impact scenarios for existing enterprise accounts', owner: 'Daniel Park' },
      { text: 'Draft customer communication plan for pricing transition', owner: 'Simone Laurent' },
      { text: 'Update pricing page and sales materials', owner: 'Amy Chen' },
      { text: 'Present final model to board at October meeting', owner: 'Rebecca Stone' },
    ],
  },
  {
    title: 'Architecture Discussion — Event Streaming Migration',
    durationMs: 61 * 60 * 1000,
    participants: [
      { name: 'Ivan Petrov', email: 'ivan@techflow.io', isHost: true },
      { name: 'Grace Williams', email: 'grace@techflow.io' },
      { name: 'Omar Hassan', email: 'omar@techflow.io' },
      { name: 'Zoe Campbell', email: 'zoe@techflow.io' },
      { name: 'Felix Müller', email: 'felix@techflow.io' },
      { name: 'Naomi Walker', email: 'naomi@techflow.io' },
      { name: 'Aaron Kim', email: 'aaron@techflow.io' },
      { name: 'Lily Chen', email: 'lily@techflow.io' },
    ],
    summary: "Architecture review of proposed Kafka migration from the current polling-based event system. Team agreed on the benefits for scalability and real-time requirements but raised concerns about operational complexity and team expertise. Decision: proceed with Kafka for new event streams only; existing polling infrastructure to be maintained for 18 months during transition.",
    actionItems: [
      { text: 'Create Kafka evaluation document with team skill assessment', owner: 'Ivan Petrov' },
      { text: 'Spike Kafka Cloud managed service vs. self-hosted cost comparison', owner: 'Omar Hassan' },
      { text: 'Design event schema for new payment events stream', owner: 'Grace Williams' },
      { text: 'Schedule Kafka training workshop for the team', owner: 'Ivan Petrov' },
    ],
  },
]
