// Shared demo seed data — used by seed-demo.ts
// All fictional people and companies

export const HERO_PARTICIPANTS = [
  { name: 'Sarah Chen', email: 'sarah.chen@acmecorp.com', isHost: true },
  { name: 'Ahmed Khan', email: 'ahmed.khan@acmecorp.com' },
  { name: 'Marcus Webb', email: 'marcus.webb@northstar.io' },
  { name: 'Priya Patel', email: 'priya.patel@northstar.io' },
  { name: 'Jordan Lee', email: 'jordan.lee@acmecorp.com' },
  { name: 'David Kim', email: 'david.kim@northstar.io' },
  { name: 'Rachel Torres', email: 'rachel.torres@acmecorp.com' },
  { name: 'Sam Nguyen', email: 'sam.nguyen@northstar.io' },
]

export const HERO_TRANSCRIPT: Array<{ speaker: string; startMs: number; endMs: number; text: string }> = [
  { speaker: 'Sarah Chen', startMs: 0, endMs: 12000, text: "Good morning everyone, thanks for joining. Let's get started on the Northstar implementation planning. We have a lot to cover today." },
  { speaker: 'Marcus Webb', startMs: 13000, endMs: 24000, text: "Thanks Sarah. From our side at Northstar, we're feeling good about the timeline but we have some concerns about the Okta SSO integration that I want to make sure we address." },
  { speaker: 'Ahmed Khan', startMs: 25000, endMs: 38000, text: "Agreed. The SSO piece is really the critical path here. Everything else can proceed in parallel, but until SSO is validated, we can't do the pilot launch." },
  { speaker: 'Priya Patel', startMs: 39000, endMs: 52000, text: "I want to understand the scope better. Are we talking about full Okta integration with SCIM provisioning, or just SAML SSO? Because those have very different timelines." },
  { speaker: 'Jordan Lee', startMs: 53000, endMs: 67000, text: "We scoped for SAML SSO in phase one. SCIM provisioning is in the roadmap for Q2 next year. But the SAML implementation itself has some complexity because Northstar has a multi-tenant Okta org." },
  { speaker: 'Marcus Webb', startMs: 68000, endMs: 84000, text: "That's correct. We have three business units each with their own Okta tenant. We need the platform to support routing based on email domain to the correct tenant. Has your team handled that before?" },
  { speaker: 'Ahmed Khan', startMs: 85000, endMs: 102000, text: "Yes, we have a multi-tenant SSO architecture. It's not trivial but it's solved. The question is whether we can get the Okta configuration from each business unit in time. We need the metadata XML from each tenant at least two weeks before the go-live." },
  { speaker: 'Sarah Chen', startMs: 103000, endMs: 118000, text: "Marcus, can you commit to getting us the Okta metadata from all three tenants by October 1st? That would give Ahmed's team the two weeks they need before our October 15th target." },
  { speaker: 'Marcus Webb', startMs: 119000, endMs: 134000, text: "I think that's achievable but I need to loop in our IT security team. David, you're closer to the IT org — what's your read on the timeline there?" },
  { speaker: 'David Kim', startMs: 135000, endMs: 151000, text: "Our IT security team typically takes one to two weeks for any changes to Okta config because it has to go through a change management process. So if we submit the request this week, we should be okay for October 1st, but there's no buffer." },
  { speaker: 'Rachel Torres', startMs: 152000, endMs: 168000, text: "I want to flag the data migration piece as well. We're migrating about 18 months of historical data from the legacy system. We haven't finalized the field mapping yet and that's a blocker for the migration team." },
  { speaker: 'Priya Patel', startMs: 169000, endMs: 185000, text: "The field mapping was supposed to be complete by last Friday. What happened? We've been waiting on the data specification from Northstar for three weeks now." },
  { speaker: 'Marcus Webb', startMs: 186000, endMs: 202000, text: "I apologize for that delay. We had a resource issue — the person who was leading the data mapping exercise took a leave of absence. David has been ramping up on it this week." },
  { speaker: 'David Kim', startMs: 203000, endMs: 219000, text: "Yes, I've taken over the data mapping work. I can commit to having the draft field mapping document to your team by end of this week, Wednesday at the latest. There are some edge cases around the legacy system's custom fields that I want to discuss separately." },
  { speaker: 'Ahmed Khan', startMs: 220000, endMs: 237000, text: "Wednesday works. Let's schedule a technical call Thursday morning to go through the edge cases. I'll need our data engineering lead on that call — is that okay with your team?" },
  { speaker: 'Sarah Chen', startMs: 238000, endMs: 254000, text: "Let's move to the security review. Priya, you mentioned in the pre-call notes that Northstar's security team wants to do a penetration test before go-live. Can you share more about the scope of that?" },
  { speaker: 'Priya Patel', startMs: 255000, endMs: 273000, text: "Our security team does a vendor assessment for any system that handles customer financial data. You're going to be processing payment information as part of the billing integration, so this is required by our security policy. We use a third-party pen testing firm." },
  { speaker: 'Jordan Lee', startMs: 274000, endMs: 291000, text: "We've been through several of these. Can your security team share the testing methodology and scope in advance? We typically need at least two weeks notice before a pen test so we can coordinate with our infrastructure team and make sure we're testing in a staging environment." },
  { speaker: 'Priya Patel', startMs: 292000, endMs: 308000, text: "Yes, I can get you the scope document next week. But I want to flag that if any critical vulnerabilities are found, we won't be able to proceed with go-live until they're remediated. That could affect the October timeline." },
  { speaker: 'Ahmed Khan', startMs: 309000, endMs: 327000, text: "Understood. We take security seriously and we've had clean pen test results in the past. But we should build remediation time into the schedule. If we assume testing happens in the last week of September, we should have findings by early October, with a week or two for any remediations." },
  { speaker: 'Sarah Chen', startMs: 328000, endMs: 345000, text: "That puts us at risk for October 15th if there are any significant findings. Let's discuss the contingency plan. What are our options if we need to slip the launch date?" },
  { speaker: 'Marcus Webb', startMs: 346000, endMs: 363000, text: "Pushing to November 1st would work from our side. We have a board presentation in mid-November that we'd like to be able to show live data in the new system. So November 1st is our hard deadline — if we miss that, we're looking at Q1 of next year." },
  { speaker: 'Rachel Torres', startMs: 364000, endMs: 381000, text: "November 1st as a fallback gives us two additional weeks. I think that's manageable as long as the SSO and data migration pieces resolve on schedule. The training program is actually ready — we built out the training materials and recorded the video walkthroughs last week." },
  { speaker: 'Sam Nguyen', startMs: 382000, endMs: 399000, text: "I can share an update on the pricing configuration. We've completed the base pricing tier setup and the discount rules are in the system. The one outstanding item is the enterprise volume discount table that Marcus's team needs to review and approve." },
  { speaker: 'Marcus Webb', startMs: 400000, endMs: 416000, text: "Sorry Sam, I know we've been slow on that. I'll personally review the discount table this week and send you our approval or any changes by Friday. That's been sitting too long." },
  { speaker: 'Sam Nguyen', startMs: 417000, endMs: 433000, text: "Thank you Marcus. Once we have the pricing approval, we can finalize the billing integration testing. We're blocked on that right now, but the code is ready to go." },
  { speaker: 'Jordan Lee', startMs: 434000, endMs: 452000, text: "On the training side, Rachel mentioned the materials are ready. I want to make sure we think about the rollout sequence. We're recommending a phased rollout — start with one business unit, run for two weeks, then expand to the other two. Does that work with your expectations?" },
  { speaker: 'David Kim', startMs: 453000, endMs: 470000, text: "A phased rollout makes sense. Our Midwest business unit is the smallest and most straightforward, so we suggest starting there. They have about 150 users versus 400 and 600 in the East and West units respectively." },
  { speaker: 'Priya Patel', startMs: 471000, endMs: 488000, text: "I support the phased approach but I want to make sure the rollout plan is captured in the contract amendment. We have contractual commitments around uptime and data availability that need to apply from day one, even for the pilot unit." },
  { speaker: 'Sarah Chen', startMs: 489000, endMs: 507000, text: "Legal is reviewing the contract amendment now. We expect to have the updated language to you by end of this week. Priya, can your legal team prioritize a quick review? We need it signed before we can proceed with the go-live." },
  { speaker: 'Priya Patel', startMs: 508000, endMs: 525000, text: "I'll flag it as urgent with our general counsel. In my experience, if we get them a clean draft by Thursday, they can turnaround in 48 hours. So that should be aligned with the October timeline." },
  { speaker: 'Ahmed Khan', startMs: 526000, endMs: 543000, text: "Let me summarize the critical path as I understand it: SSO metadata by October 1st, security pen test in the last week of September with findings by October 7th, data migration field mapping by Wednesday, pricing approval by Friday, contract amendment signed by end of next week. Does that capture the key dependencies?" },
  { speaker: 'Marcus Webb', startMs: 544000, endMs: 562000, text: "That's accurate from my perspective. I'd add that we need the training schedule finalized this week as well, so our business unit admins can start blocking time on their calendars for the Midwest rollout." },
  { speaker: 'Rachel Torres', startMs: 563000, endMs: 580000, text: "I can have the training schedule to David by tomorrow EOD. We're planning three sessions of two hours each — Monday and Wednesday over three weeks. So starting October 21st for the Midwest group." },
  { speaker: 'Sam Nguyen', startMs: 581000, endMs: 598000, text: "One thing I want to raise before we close — the staging environment performance. We've been seeing some slowness in the staging environment during the load testing we did last week. Nothing that affects the go-live, but it's something we should track. Ahmed, can you look into the database query optimization?" },
  { speaker: 'Ahmed Khan', startMs: 599000, endMs: 617000, text: "Yes, I saw the performance report. We have some N+1 query issues in the reporting module that are causing the slowness under load. We expect to have that resolved in the release next Tuesday. It won't affect the go-live timeline." },
  { speaker: 'Sarah Chen', startMs: 618000, endMs: 635000, text: "Great. Let's make sure that release note gets shared with Northstar's team so they're aware. Any other blockers or concerns before we wrap up?" },
  { speaker: 'Jordan Lee', startMs: 636000, endMs: 653000, text: "One small thing — we need Northstar to whitelist our IP ranges for the data migration. We sent those over two weeks ago but haven't gotten confirmation. David, can you follow up on that today?" },
  { speaker: 'David Kim', startMs: 654000, endMs: 671000, text: "I apologize, that fell through the cracks. I'll escalate to our IT team immediately after this call. We should have confirmation by end of day today." },
  { speaker: 'Marcus Webb', startMs: 672000, endMs: 689000, text: "I want to formally record that we're committed to the October 15th launch date with November 1st as the fallback. Northstar has allocated significant internal resources to this project and we need the implementation partner to hit these dates. We're counting on Acme Corp." },
  { speaker: 'Sarah Chen', startMs: 690000, endMs: 708000, text: "We understand, Marcus. We have the resources in place and the plan is solid. The dependencies we've identified today are all manageable. Let's make sure we have a brief check-in next Monday to verify everything is on track." },
  { speaker: 'Ahmed Khan', startMs: 709000, endMs: 727000, text: "I'll send a meeting invite for Monday at 10am Eastern. Before then, I'll have action items documented and shared with everyone so there are no surprises. This is the most complex integration we've done this year and I want to make sure we stay ahead of any issues." },
  { speaker: 'Priya Patel', startMs: 728000, endMs: 745000, text: "Agreed. One final note from our side — we have a Northstar all-hands meeting on October 3rd where our CEO will announce the new platform rollout. So hitting the October 15th date is important for optics as well as operations." },
  { speaker: 'Sarah Chen', startMs: 746000, endMs: 763000, text: "We will make it happen. Thank you all for a productive call. Ahmed, can you take the notes and action items? I'll add any follow-ups from my end." },
  { speaker: 'Ahmed Khan', startMs: 764000, endMs: 780000, text: "On it. I'll have the action items out within an hour of the call. Talk to everyone next Monday. Thank you." },
  { speaker: 'Marcus Webb', startMs: 781000, endMs: 793000, text: "Thank you everyone. Looking forward to a successful launch." },
  { speaker: 'Priya Patel', startMs: 794000, endMs: 803800, text: "Thanks, have a great day." },
]

export const HERO_SUMMARY = {
  overview: "Acme Corp and Northstar held an enterprise implementation planning call covering the critical path to the October 15th go-live date. Key topics included Okta SSO integration complexity with Northstar's multi-tenant environment, data migration field mapping delays, security penetration testing requirements, pricing configuration approval, training schedule, and contract amendment status. A November 1st hard fallback date was established, with the October 3rd all-hands announcement creating additional urgency for the primary date.",
  keyPoints: [
    "Okta SSO integration is the critical path — requires metadata from all 3 business unit tenants by October 1st",
    "Security pen test planned for last week of September; critical findings could slip go-live",
    "Data migration field mapping was delayed due to resource issue; David Kim committed to Wednesday delivery",
    "Pricing enterprise discount table approval needed from Marcus Webb by Friday",
    "Phased rollout starting with Midwest business unit (150 users) recommended",
    "Contract amendment under legal review; expected to Northstar by Thursday",
    "Performance issues in staging environment (N+1 queries in reporting) to be fixed in Tuesday release",
    "Northstar CEO announcing platform rollout at October 3rd all-hands, creating external deadline",
  ],
  decisions: [
    { text: "October 15th primary go-live date with November 1st as hard fallback deadline", status: 'confirmed' as const },
    { text: "Phased rollout: start with Midwest business unit (150 users), then expand to East and West", status: 'confirmed' as const },
    { text: "Security pen test to occur in last week of September using Northstar's third-party firm", status: 'confirmed' as const },
    { text: "SAML SSO only in phase 1; SCIM provisioning deferred to Q2 next year", status: 'confirmed' as const },
    { text: "Training sessions: three 2-hour sessions, Monday/Wednesday, starting October 21st for Midwest", status: 'tentative' as const },
  ],
  actionItems: [
    { text: "Submit Okta SSO change management request to IT security team this week", owner: 'David Kim', dueDate: '2025-09-19' },
    { text: "Deliver draft data migration field mapping document", owner: 'David Kim', dueDate: '2025-09-17' },
    { text: "Schedule technical call Thursday to review data migration edge cases", owner: 'Ahmed Khan', dueDate: '2025-09-18' },
    { text: "Review and approve enterprise volume discount table", owner: 'Marcus Webb', dueDate: '2025-09-19' },
    { text: "Send Northstar the security pen test scope document", owner: 'Priya Patel', dueDate: '2025-09-22' },
    { text: "Deliver updated contract amendment to Northstar's legal team", owner: 'Sarah Chen', dueDate: '2025-09-18' },
    { text: "Finalize and send training schedule to David Kim", owner: 'Rachel Torres', dueDate: '2025-09-16' },
    { text: "Escalate IP whitelist request to IT team", owner: 'David Kim', dueDate: '2025-09-15' },
    { text: "Send meeting invite and action items to all participants", owner: 'Ahmed Khan', dueDate: '2025-09-15' },
    { text: "Resolve N+1 query issues in reporting module", owner: 'Ahmed Khan', dueDate: '2025-09-23' },
  ],
  topics: [
    { title: 'Okta SSO Integration', summary: 'Multi-tenant Okta setup requires metadata from 3 business units. Ahmed confirmed multi-tenant architecture is solved. October 1st deadline for metadata delivery from Northstar.', startMs: 13000, endMs: 237000 },
    { title: 'Data Migration', summary: 'Field mapping delayed due to team resource issue. David Kim taking over, commits to Wednesday delivery. Technical call Thursday to address edge cases in legacy custom fields.', startMs: 152000, endMs: 237000 },
    { title: 'Security Review', summary: 'Northstar requires third-party pen test before go-live for any system handling customer financial data. Scope document coming next week. Critical findings could delay October 15th launch.', startMs: 238000, endMs: 327000 },
    { title: 'Launch Timeline & Contingency', summary: 'October 15th primary date confirmed. November 1st hard fallback. Northstar CEO all-hands on October 3rd adds external pressure. Phased rollout starting with Midwest unit.', startMs: 328000, endMs: 470000 },
    { title: 'Pricing & Billing', summary: 'Base pricing and discount rules complete. Enterprise volume discount table pending Marcus approval by Friday. Billing integration testing blocked pending pricing approval.', startMs: 382000, endMs: 433000 },
    { title: 'Training & Rollout', summary: 'Training materials and video walkthroughs complete. Three 2-hour sessions planned Monday/Wednesday for three weeks, starting October 21st for Midwest group. Schedule to be finalized by tomorrow.', startMs: 363000, endMs: 580000 },
    { title: 'Open Issues & Infrastructure', summary: 'Staging environment performance issues identified in load testing (N+1 queries in reporting). Fix in Tuesday release. IP whitelist for data migration overdue from Northstar IT.', startMs: 581000, endMs: 671000 },
    { title: 'Next Steps & Close', summary: 'Monday 10am check-in scheduled. Ahmed to send action items within an hour. Marcus formally committed Northstar to the October 15th date.', startMs: 672000, endMs: 803800 },
  ],
  highlights: [
    { title: 'SSO Is The Critical Path', startMs: 85000, endMs: 102000 },
    { title: 'October 1st Metadata Deadline', startMs: 103000, endMs: 134000 },
    { title: 'Pen Test Could Delay Launch', startMs: 255000, endMs: 308000 },
    { title: 'November 1st Hard Fallback', startMs: 346000, endMs: 381000 },
    { title: 'CEO All-Hands Announcement Context', startMs: 728000, endMs: 763000 },
  ],
}

export const SEED_MEETINGS = [
  {
    title: 'Weekly Product Sync',
    durationMs: 38 * 60 * 1000,
    participants: [
      { name: 'Elena Rodriguez', email: 'elena@techflow.io', isHost: true },
      { name: 'Ben Carter', email: 'ben@techflow.io' },
      { name: 'Lena Park', email: 'lena@techflow.io' },
      { name: 'Alex Morrison', email: 'alex@techflow.io' },
      { name: 'Jamie Walsh', email: 'jamie@techflow.io' },
      { name: 'Chris Okafor', email: 'chris@techflow.io' },
    ],
    summary: "Weekly sync covering sprint velocity, three new feature flags shipped to production, and discussion of the upcoming API versioning strategy. Team agreed to deprecate v1 endpoints by March next year.",
    actionItems: [
      { text: 'Update API deprecation timeline in documentation', owner: 'Chris Okafor' },
      { text: 'Schedule architecture review for v2 API design', owner: 'Alex Morrison' },
      { text: 'Share sprint metrics with leadership by Friday', owner: 'Elena Rodriguez' },
    ],
  },
  {
    title: 'Customer Discovery — Redwood Financial',
    durationMs: 47 * 60 * 1000,
    participants: [
      { name: 'Maya Singh', email: 'maya@acmecorp.com', isHost: true },
      { name: 'Tom Bradley', email: 'tom@redwoodfinancial.com' },
      { name: 'Lisa Chen', email: 'lisa@redwoodfinancial.com' },
      { name: 'Kevin Park', email: 'kevin@acmecorp.com' },
      { name: 'Nadia Osei', email: 'nadia@redwoodfinancial.com' },
    ],
    summary: "Discovery call with Redwood Financial exploring their compliance reporting challenges. Key pain points: manual report generation taking 3-4 days per quarter, data spread across 6 different systems, audit trail gaps. Strong fit for automated reporting and data consolidation capabilities.",
    actionItems: [
      { text: 'Send product demo recording and pricing proposal', owner: 'Maya Singh' },
      { text: 'Prepare compliance automation case studies', owner: 'Kevin Park' },
      { text: 'Schedule technical deep dive with Redwood IT team', owner: 'Maya Singh' },
    ],
  },
  {
    title: 'Candidate Interview — Backend Engineer',
    durationMs: 52 * 60 * 1000,
    participants: [
      { name: 'Diana Chen', email: 'diana@techflow.io', isHost: true },
      { name: 'Arjun Sharma', email: 'arjun.sharma@candidate.com' },
      { name: 'Robert Kim', email: 'robert@techflow.io' },
    ],
    summary: "Technical interview with Arjun Sharma for the Senior Backend Engineer role. Strong performance on distributed systems design question. Concerns about depth of experience with PostgreSQL query optimization. Demonstrated excellent problem-solving approach and communication skills. Recommend advancing to final round with engineering leadership.",
    actionItems: [
      { text: 'Submit candidate evaluation form to recruiting', owner: 'Diana Chen' },
      { text: 'Schedule final round panel interview', owner: 'Diana Chen' },
      { text: 'Send take-home assessment in parallel', owner: 'Robert Kim' },
    ],
  },
  {
    title: 'Design Review — Dashboard Redesign',
    durationMs: 34 * 60 * 1000,
    participants: [
      { name: 'Sofia Martinez', email: 'sofia@techflow.io', isHost: true },
      { name: 'Jake Thompson', email: 'jake@techflow.io' },
      { name: 'Yuki Tanaka', email: 'yuki@techflow.io' },
      { name: 'Mia Johnson', email: 'mia@techflow.io' },
      { name: 'Caleb Foster', email: 'caleb@techflow.io' },
    ],
    summary: "Design review of the new analytics dashboard. Approved the data visualization approach and chart library selection. Feedback to increase information density in the summary cards and reconsider the color system for accessibility compliance. Next step: update Figma prototypes and schedule engineering handoff.",
    actionItems: [
      { text: 'Update dashboard Figma with higher density layout', owner: 'Sofia Martinez' },
      { text: 'Run color contrast accessibility audit', owner: 'Yuki Tanaka' },
      { text: 'Create engineering specification document', owner: 'Jake Thompson' },
    ],
  },
  {
    title: 'Founder 1:1 — Q4 Planning',
    durationMs: 41 * 60 * 1000,
    participants: [
      { name: 'Nathan Brooks', email: 'nathan@techflow.io', isHost: true },
      { name: 'Olivia Zhang', email: 'olivia@techflow.io' },
    ],
    summary: "Quarterly planning session covering revenue targets, hiring priorities, and strategic focus areas. Agreed to prioritize enterprise segment in Q4, pause mid-market expansion until Q1. Three VP-level hires to close before December: VP Sales, VP Customer Success, and Head of Engineering.",
    actionItems: [
      { text: 'Begin VP Sales search, open JD by Monday', owner: 'Nathan Brooks' },
      { text: 'Update board deck with Q4 targets and hiring plan', owner: 'Olivia Zhang' },
      { text: 'Schedule board call for October 20th', owner: 'Olivia Zhang' },
    ],
  },
  {
    title: 'Sprint Planning — Sprint 43',
    durationMs: 56 * 60 * 1000,
    participants: [
      { name: 'Marcus Lee', email: 'marcus@techflow.io', isHost: true },
      { name: 'Sarah Kim', email: 'sarah.k@techflow.io' },
      { name: 'Dylan Russo', email: 'dylan@techflow.io' },
      { name: 'Aisha Patel', email: 'aisha@techflow.io' },
      { name: 'Erik Svensson', email: 'erik@techflow.io' },
      { name: 'Priya Rajan', email: 'priya.r@techflow.io' },
      { name: 'Leo Nakamura', email: 'leo@techflow.io' },
    ],
    summary: "Sprint 43 planning with 52 story points committed. Key deliverables: complete notification system refactor, ship audit logging MVP, and begin work on the export functionality. Carried over 8 points from sprint 42 related to auth service edge cases. Team velocity stable at 48-55 points.",
    actionItems: [
      { text: 'Finalize notification service API contract before Monday standup', owner: 'Dylan Russo' },
      { text: 'Set up export module scaffold and share PR', owner: 'Sarah Kim' },
      { text: 'Document auth service edge cases for knowledge base', owner: 'Erik Svensson' },
    ],
  },
  {
    title: 'Customer Success Check-in — Vertex Analytics',
    durationMs: 29 * 60 * 1000,
    participants: [
      { name: 'Hannah Moore', email: 'hannah@acmecorp.com', isHost: true },
      { name: 'Tyler Grant', email: 'tyler@vertexanalytics.com' },
      { name: 'Chloe Bennett', email: 'chloe@vertexanalytics.com' },
      { name: 'James Liu', email: 'james@acmecorp.com' },
    ],
    summary: "Quarterly business review with Vertex Analytics. NPS score improved from 6 to 8 since last quarter. Two open support tickets resolved. Discussion of expanding usage to the European team. Renewal in 3 months — customer expressed satisfaction and intent to renew with potential seat expansion.",
    actionItems: [
      { text: 'Prepare European expansion pricing proposal', owner: 'James Liu' },
      { text: 'Share updated roadmap highlighting European data residency', owner: 'Hannah Moore' },
      { text: 'Schedule renewal discussion for next month', owner: 'Hannah Moore' },
    ],
  },
  {
    title: 'Pricing Review — Enterprise Tier Restructure',
    durationMs: 45 * 60 * 1000,
    participants: [
      { name: 'Rebecca Stone', email: 'rebecca@techflow.io', isHost: true },
      { name: 'Daniel Park', email: 'daniel@techflow.io' },
      { name: 'Amy Chen', email: 'amy@techflow.io' },
      { name: 'Victor Okafor', email: 'victor@techflow.io' },
      { name: 'Simone Laurent', email: 'simone@techflow.io' },
      { name: 'Chris Tanaka', email: 'chris.t@techflow.io' },
    ],
    summary: "Pricing committee review of proposed enterprise tier restructure. Decision to move from seat-based to usage-based pricing for enterprise customers with 500+ seats. New model includes a base platform fee plus consumption tiers. Expected to improve gross margin by 8-12 points. Rollout to existing customers with 6-month grandfathering period.",
    actionItems: [
      { text: 'Model financial impact scenarios for existing enterprise accounts', owner: 'Daniel Park' },
      { text: 'Draft customer communication plan for pricing transition', owner: 'Simone Laurent' },
      { text: 'Update pricing page and sales materials', owner: 'Amy Chen' },
      { text: 'Present final model to board at October meeting', owner: 'Rebecca Stone' },
    ],
  },
  {
    title: 'Architecture Discussion — Event Streaming Migration',
    durationMs: 61 * 60 * 1000,
    participants: [
      { name: 'Ivan Petrov', email: 'ivan@techflow.io', isHost: true },
      { name: 'Grace Williams', email: 'grace@techflow.io' },
      { name: 'Omar Hassan', email: 'omar@techflow.io' },
      { name: 'Zoe Campbell', email: 'zoe@techflow.io' },
      { name: 'Felix Müller', email: 'felix@techflow.io' },
      { name: 'Naomi Walker', email: 'naomi@techflow.io' },
      { name: 'Aaron Kim', email: 'aaron@techflow.io' },
      { name: 'Lily Chen', email: 'lily@techflow.io' },
    ],
    summary: "Architecture review of proposed Kafka migration from the current polling-based event system. Team agreed on the benefits for scalability and real-time requirements but raised concerns about operational complexity and team expertise. Decision: proceed with Kafka for new event streams only; existing polling infrastructure to be maintained for 18 months during transition.",
    actionItems: [
      { text: 'Create Kafka evaluation document with team skill assessment', owner: 'Ivan Petrov' },
      { text: 'Spike Kafka Cloud managed service vs. self-hosted cost comparison', owner: 'Omar Hassan' },
      { text: 'Design event schema for new payment events stream', owner: 'Grace Williams' },
      { text: 'Schedule Kafka training workshop for the team', owner: 'Ivan Petrov' },
    ],
  },
]
